name: fouda_portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_animate: ^4.2.0+1
  rive: ^0.11.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.1.4
  custom_lint: ^0.5.1
  riverpod_lint: ^2.0.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/anims/

  fonts:
    - family: PersonalPortfolioIcons
      fonts:
        - asset: assets/fonts/PersonalPortfolioIcons.ttf
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
        - asset: assets/fonts/Product Sans Bold.ttf
          weight: 900
        - asset: assets/fonts/Product Sans Italic.ttf
          style: italic
